version: 2.1

workflows:
  build-docker-image:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: docker build -t wedassign:latest .



