version: 2.1

workflows:
  build-docker-image:
    jobs:
      - build
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t allan/webassign:latest .
      - run:
          name: Push image to docker hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker image tag allan/webassign:latest allanns/webassign:latest
            docker image push allanns/webassign:latest
