apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendyapp
spec:
  selector:
    matchLabels:
      name: trendyapp
  template:
    metadata:
      labels:
        name: trendyapp
    spec:
      containers:
        - name: app
          image: allanns/webassign:latest
          ports:
            - containerPort: 8080